// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7brGyFrhcvXWPlsE_2UJIJg6hdQIV-q8',
    appId: '1:1092818917014:web:673dbc8edc1c6ba74754b7',
    messagingSenderId: '1092818917014',
    projectId: 'video-streaming-tutorial-9686c',
    authDomain: 'video-streaming-tutorial-9686c.firebaseapp.com',
    storageBucket: 'video-streaming-tutorial-9686c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0RSel2Cf_oKeRgRN9rsUdg68mfIPu80',
    appId: '1:1092818917014:android:e791eb21426a79974754b7',
    messagingSenderId: '1092818917014',
    projectId: 'video-streaming-tutorial-9686c',
    storageBucket: 'video-streaming-tutorial-9686c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqbVDgatPqmAlgKELi7PtsRgpfpAdr1c',
    appId: '1:1092818917014:ios:aa8e896c6e5b018c4754b7',
    messagingSenderId: '1092818917014',
    projectId: 'video-streaming-tutorial-9686c',
    storageBucket: 'video-streaming-tutorial-9686c.appspot.com',
    iosBundleId: 'com.example.videoStreamingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqqbVDgatPqmAlgKELi7PtsRgpfpAdr1c',
    appId: '1:1092818917014:ios:aa8e896c6e5b018c4754b7',
    messagingSenderId: '1092818917014',
    projectId: 'video-streaming-tutorial-9686c',
    storageBucket: 'video-streaming-tutorial-9686c.appspot.com',
    iosBundleId: 'com.example.videoStreamingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7brGyFrhcvXWPlsE_2UJIJg6hdQIV-q8',
    appId: '1:1092818917014:web:8589c3db67379d6b4754b7',
    messagingSenderId: '1092818917014',
    projectId: 'video-streaming-tutorial-9686c',
    authDomain: 'video-streaming-tutorial-9686c.firebaseapp.com',
    storageBucket: 'video-streaming-tutorial-9686c.appspot.com',
  );
}
